services:
  nginx:
    depends_on:
      - prometheus
      - prometheus-manager
      - grafana
    image: nginx:1.25.5-alpine
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
    networks:
      - monitoring
  prometheus-manager:
    depends_on:
      - prometheus
    image: cotidie/prometheus-manager
    stdin_open: true
    tty: true
    container_name: prometheus-manager
    ports:
      - 8001:8001
    command:
      - '--config=/app/prometheus.yaml'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yaml:/app/prometheus.yaml
      - ./pipe/docker:/pipe/docker
    networks:
      - monitoring
volumes:
  prom_data:

networks:
  monitoring:
    driver: bridge
