# 위치: /grad-project/prometheus/prometheus.yaml
global:
  scrape_interval: 30s # set the scraping interval to 30 seconds.
  evaluation_interval: 15s # the interval for evaluating rules.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["localhost:9090"]