#!/bin/bash


# Command: register_router <ip> <port>
# Description: 라우터의 IP, 메트릭 노출 포트번호를 받아 프로메테우스에 등록하는 스크립트

IP=$1
PORT=$2
API_REGISTER="prometheus-manager.daily-cotidie.com/api/target/add"

if [[ -z "$IP" ]]; then
    printf '[register_router] No IP address is delivered. \n'
    exit 1;
fi

if [[ -z "$PORT" ]]; then
    printf '[register_router] No port number for metrics export is delivered. \n'
    exit 1;
fi

curl $API_REGISTER \
    --request POST \
    --data-binary "{\"ip\":\"$IP:$PORT\"}"